### ISSUE TITLE
body failed validation: body.parent.page_id should be defined, instead was undefined.

### ISSUE THREAD

**Issue by saber969** [selfboot/html2notion#11]
![image](https://github.com/selfboot/html2notion/assets/22891634/2004648f-0da1-4126-9317-300bcc91944d)

**Comment by selfboot** [comment]
> ![image](https://user-images.githubusercontent.com/22891634/238554673-2004648f-0da1-4126-9317-300bcc91944d.png)

可以提供下html的头部内容吗？

**Comment by saber969** [comment]
[新建文件夹 (2).zip](https://github.com/selfboot/html2notion/files/11493207/2.zip)
