### ISSUE TITLE
上传一直失败

### ISSUE THREAD

**Issue by zhl82** [selfboot/html2notion#2]
'gbk' codec can't decode byte

![屏幕截图 2023-05-03 105938](https://user-images.githubusercontent.com/42397498/235825201-98e0c20a-cf43-4c1c-9968-92679907cd38.png)

**Comment by vsnotme** [comment]
好像导出的格式不对，新版导出的html都是一连串在一个文件夹里面

**Comment by zhl82** [comment]
能不能出个详细的教程？我尝试上传demo中的测试文件都有一半失败了

**Comment by selfboot** [comment]
> 好像导出的格式不对，新版导出的html都是一连串在一个文件夹里面

是在一个文件夹，一个笔记一个文件，直接导入整个目录就好

**Comment by selfboot** [comment]
> 'gbk' codec can't decode byte
> 
> ![屏幕截图 2023-05-03 105938](https://user-images.githubusercontent.com/42397498/235825201-98e0c20a-cf43-4c1c-9968-92679907cd38.png)

应该是不同平台导出来的编码不一样，我稍后修复下，支持下不同编码

**Comment by selfboot** [comment]
> 能不能出个详细的教程？我尝试上传demo中的测试文件都有一半失败了

可以贴一下错误截图不，最好是提供一下失败的 html 文件

**Comment by selfboot** [comment]
> 能不能出个详细的教程？我尝试上传demo中的测试文件都有一半失败了

demos 里的是我搞坏了，已经修复了，下个版本带上去。

**Comment by selfboot** [comment]
> 能不能出个详细的教程？我尝试上传demo中的测试文件都有一半失败了

@zhl82 试试  [v0.1.8](https://github.com/selfboot/html2notion/releases/tag/v0.1.8)

**Comment by zhl82** [comment]
![image](https://github.com/selfboot/html2notion/assets/42397498/d6bb4253-1b4a-43a3-b040-2abb3c604dcf)
从印象导出了1个html文件，试着上传，没成功。我不是程序员，也不知道哪里姿势不对。

**Comment by selfboot** [comment]
> ![image](https://user-images.githubusercontent.com/42397498/237708547-d6bb4253-1b4a-43a3-b040-2abb3c604dcf.png) 从印象导出了1个html文件，试着上传，没成功。我不是程序员，也不知道哪里姿势不对。

可以提供下html文件吗，这个是文件编码gbk的问题

**Comment by selfboot** [comment]
0.1.9 可以啦
