### ISSUE TITLE
可以正常使用，但是几乎都是只导入了标题部分。难道我的姿势有误吗？

### ISSUE THREAD

**Issue by vsnotme** [selfboot/html2notion#3]
<img width="714" alt="Screenshot 2023-05-04 at 3 35 03 PM" src="https://user-images.githubusercontent.com/22863236/236140859-f914f416-d538-492a-8093-02c3bfc96080.png">

**Comment by selfboot** [comment]
可以提供下 html 文件吗，我看看

**Comment by vsnotme** [comment]
[su.zip](https://github.com/selfboot/html2notion/files/11405346/su.zip)

**Comment by selfboot** [comment]
> [su.zip](https://github.com/selfboot/html2notion/files/11405346/su.zip)

commit 8959ddd2faf54337bf5e03b4da13fe8f61183893 fix .

**Comment by selfboot** [comment]
Upgrade to https://github.com/selfboot/html2notion/releases/tag/v0.1.8
