### ISSUE TITLE
现在notion自带的evernote导入可用性不错。我目前的方案是国内版印象转换到国际版，然后用notion自带的导入

### ISSUE THREAD

**Issue by vsnotme** [selfboot/html2notion#4]

**Comment by selfboot** [comment]
国内怎么转国际，可以详细说一下吗？我试过不太行，后面就没弄了

**Comment by vsnotme** [comment]
这是在windows下操作的，应该都大差不差。首先下载老版本Evernote_7.0.18.5138或其它可用版本安装，在网上找到的。然后这个版本可以导出.enex文件。下载安装登录国际版的软件（目前国际版是支持enex 导入的），按个人需求删光里面的笔记，然后导入事先在国内版导出的enex文件，然后可能会遇到导入后最后编辑时间混乱的问题，但是没关系，在后续的使用nition自带的导入功能时，时间日期是正常的。以上就是大致步骤。我已经安稳搞定了，印象笔记滚粗！

**Comment by selfboot** [comment]
> 这是在windows下操作的，应该都大差不差。首先下载老版本Evernote_7.0.18.5138或其它可用版本安装，在网上找到的。然后这个版本可以导出.enex文件。下载安装登录国际版的软件（目前国际版是支持enex 导入的），按个人需求删光里面的笔记，然后导入事先在国内版导出的enex文件，然后可能会遇到导入后最后编辑时间混乱的问题，但是没关系，在后续的使用nition自带的导入功能时，时间日期是正常的。以上就是大致步骤。我已经安稳搞定了，印象笔记滚粗！

我是mac，现在没啥办法能导出 enex 版本了，只有 html 和 notes 格式的。
后续这个工具会持续扩展，只要是html的内容，比如网页地址之类的，都可以用这个快速导入notion
