### ISSUE TITLE
'Html2JsonYinXiang' object has no attribute 'convert_fail'

### ISSUE THREAD

**Issue by HITlilingzhi** [selfboot/html2notion#7]
<img width="889" alt="image" src="https://github.com/selfboot/html2notion/assets/14293981/176b0b43-ee38-4195-a7f6-6d53c1de6d48">

如图，倒入一个印象笔记导出的html，显示如上报错

**Comment by selfboot** [comment]
已知问题，我已经修复了，下个版本就好了

**Comment by HITlilingzhi** [comment]
收到，请问下个版本什么时候发布？

**Comment by selfboot** [comment]
预计这周内，会增加一些转换质量监控

**Comment by HITlilingzhi** [comment]
好滴，辛苦啦！

**Comment by selfboot** [comment]
Upgrade to [v0.1.8](https://github.com/selfboot/html2notion/releases/tag/v0.1.8)
