### ISSUE TITLE
body failed validation: body.parent.page_id should bedefined, instead was `undefined`.

### ISSUE THREAD

**Issue by 422926799** [selfboot/html2notion#8]
![image](https://github.com/selfboot/html2notion/assets/29516567/eb2cf8eb-dbe2-4e34-a4a7-c141f4edc128)

Database ID分割试过了，不分割也试过了。一直报这个

**Comment by selfboot** [comment]
> 422926799

应该是解析html类型失败了，可以贴下html的内容吗？或者只给我head部分就行

**Comment by selfboot** [comment]
增加了一些错误的诊断信息输出，这样遇见这个问题的时候，不用提供html也能做到header里的信息。
