### ISSUE TITLE
 API token is invalid.

### ISSUE THREAD

**Issue by saber969** [selfboot/html2notion#9]
![image](https://github.com/selfboot/html2notion/assets/22891634/42c9db3b-c31f-45e6-bb8a-6055bb9b3c16)
这样填写对吗，一直报错

**Comment by selfboot** [comment]
> ![image](https://user-images.githubusercontent.com/22891634/238299677-42c9db3b-c31f-45e6-bb8a-6055bb9b3c16.png) 这样填写对吗，一直报错

把 `< >` 去掉就行了
